In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlalchemy as sql

%matplotlib inline

In [3]:
all_songs = pd.read_csv(r'clean_playlist.csv')
all_songs.head()

,Unnamed: 0,Unnamed: 0.1,explicit,id,name,popularity,danceability,energy,key,loudness,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms_y,time_signature,release_date,artist
0,0,0,False,0FE9t6xYkqWXU2ahLh6D8X,Shape of You,72,0.825,0.652,C#/Db,-3.183,...,0.0802,0.58100,0.000000,0.0931,0.931,95.977,233713,4,2017-01-06,Ed Sheeran
1,1,1,False,5ZULALImTm80tzUbYQYM9d,Dance Monkey,79,0.824,0.588,F#/Gb,-6.400,...,0.0924,0.69200,0.000104,0.1490,0.513,98.027,209438,4,2019-08-29,Tones And I
2,2,2,True,7wGoVu4Dady5GV0Sv4UIsx,rockstar,1,0.577,0.522,F,-6.594,...,0.0984,0.13000,0.000090,0.1420,0.119,159.772,218320,4,2017-09-15,Post Malone
3,3,3,False,1xznGGDReH1oQq0xzbwXa3,One Dance,3,0.791,0.619,C#/Db,-5.886,...,0.0532,0.00784,0.004230,0.3510,0.371,103.989,173987,4,2016-05-06,Drake
4,4,4,False,7BKLCZ1jbUBVqRi2FVlTVw,Closer,85,0.748,0.524,Ab,-5.599,...,0.0338,0.41400,0.000000,0.1110,0.661,95.010,244960,4,2016-07-29,The Chainsmokers

In [4]:
all_songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4153 entries, 0 to 4152
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        4153 non-null   int64
 1   Unnamed: 0.1      4153 non-null   int64
 2   explicit          4153 non-null   bool
 3   id                4153 non-null   object
 4   name              4153 non-null   object
 5   popularity        4153 non-null   int64
 6   danceability      4153 non-null   float64
 7   energy            4153 non-null   float64
 8   key               4153 non-null   object
 9   loudness          4153 non-null   float64
 10  mode              4153 non-null   object
 11  speechiness       4153 non-null   float64
 12  acousticness      4153 non-null   float64
 13  instrumentalness  4153 non-null   float64
 14  liveness          4153 non-null   float64
 15  valence           4153 non-null   float64
 16  tempo             4153 non-null   float64
 17  duration_ms_y     4153 non-null   int64
 18  time_signature    4153 non-null   int64
 19  release_date      4153 non-null   object
 20  artist            4126 non-null   object
dtypes: bool(1), float64(9), int64(5), object(6)
memory usage: 653.1+ KB

In [5]:
all_songs.describe()

,Unnamed: 0,Unnamed: 0.1,popularity,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms_y,time_signature
count,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000,4153.000000
mean,2076.000000,2076.000000,56.550927,0.643721,0.666766,-6.401435,0.099940,0.198145,0.020169,0.178452,0.506097,121.428854,224229.275223,3.970864
std,1199.012163,1199.012163,27.962538,0.151815,0.179685,2.726780,0.097237,0.234234,0.100736,0.140017,0.228790,28.403086,51991.293722,0.254759
min,0.000000,0.000000,0.000000,0.149000,0.054100,-25.398000,0.022400,0.000006,0.000000,0.019700,0.033800,46.718000,60453.000000,1.000000
25%,1038.000000,1038.000000,55.000000,0.544000,0.552000,-7.601000,0.038300,0.023100,0.000000,0.092800,0.328000,99.019000,192573.000000,4.000000
50%,2076.000000,2076.000000,68.000000,0.660000,0.688000,-5.874000,0.058000,0.101000,0.000001,0.122000,0.502000,120.007000,216733.000000,4.000000
75%,3114.000000,3114.000000,74.000000,0.754000,0.801000,-4.563000,0.118000,0.290000,0.000146,0.221000,0.685000,139.261000,245426.000000,4.000000
max,4152.000000,4152.000000,100.000000,0.974000,0.995000,0.175000,0.856000,0.994000,0.985000,0.979000,0.980000,211.974000,558933.000000,5.000000

In [6]:
import sqlalchemy as sql